// Mocks generated by Mockito 5.4.4 from annotations
// in dress/test/mocks/mock_firebase_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i6;
import 'package:dress/services/firebase_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthUser_0 extends _i1.SmartFake implements _i2.AuthUser {
  _FakeAuthUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i2.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i2.AuthUser?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i3.Stream<_i2.AuthUser?>.empty(),
      ) as _i3.Stream<_i2.AuthUser?>);

  @override
  _i3.Future<_i2.AuthUser> signUpWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<_i2.AuthUser>.value(_FakeAuthUser_0(
          this,
          Invocation.method(
            #signUpWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i3.Future<_i2.AuthUser>);

  @override
  _i3.Future<_i2.AuthUser> loginWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<_i2.AuthUser>.value(_FakeAuthUser_0(
          this,
          Invocation.method(
            #loginWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i3.Future<_i2.AuthUser>);

  @override
  _i3.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> uploadImage(
    _i4.Uint8List? fileBytes,
    String? extension,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [
            fileBytes,
            extension,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImage,
            [
              fileBytes,
              extension,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> saveClothingData({
    required String? imageUrl,
    required String? category,
    required String? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClothingData,
          [],
          {
            #imageUrl: imageUrl,
            #category: category,
            #tags: tags,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i6.QuerySnapshot<Object?>> getClothesStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getClothesStream,
          [],
        ),
        returnValue: _i3.Stream<_i6.QuerySnapshot<Object?>>.empty(),
      ) as _i3.Stream<_i6.QuerySnapshot<Object?>>);

  @override
  _i3.Future<void> updateClothingData({
    required String? docId,
    required Map<String, dynamic>? updatedData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateClothingData,
          [],
          {
            #docId: docId,
            #updatedData: updatedData,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteClothingData(String? docId) => (super.noSuchMethod(
        Invocation.method(
          #deleteClothingData,
          [docId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveOOTDData({
    required String? imageUrl,
    required String? description,
    required List<Map<String, dynamic>>? taggedClothes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOOTDData,
          [],
          {
            #imageUrl: imageUrl,
            #description: description,
            #taggedClothes: taggedClothes,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i6.QuerySnapshot<Object?>> getOOTDStream() => (super.noSuchMethod(
        Invocation.method(
          #getOOTDStream,
          [],
        ),
        returnValue: _i3.Stream<_i6.QuerySnapshot<Object?>>.empty(),
      ) as _i3.Stream<_i6.QuerySnapshot<Object?>>);

  @override
  _i3.Future<void> deleteOOTDData(String? docId) => (super.noSuchMethod(
        Invocation.method(
          #deleteOOTDData,
          [docId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
